FROM docker.io/library/fedora:39

RUN rpm --import https://falco.org/repo/falcosecurity-packages.asc

COPY falcosecurity-rpm-dev-testdomain.repo /etc/yum.repos.d/falcosecurity-dev.repo

RUN dnf update -y

RUN dnf install -y falco

RUN falco --version
